### ISSUE TITLE
Assign titles to the sections?

### ISSUE THREAD

**Issue by mbroe** [csi4999-mims/documentation#135]
We have sections 1-13, only the 13th of which has a title, viz. "References."  The rest are simply "Section 1," "Section 2," and so on.  We should decide whether we want these sections to have titles, and if so, what those titles should be.

- [x] 01 Project Vision
    - 01.01.Background.md
    - 01.02.Socio-economicImpactBusinessObjectivesandGapAnalysis.md
    - 01.03.Securityandethicalconcerns.md
    - 01.04.GlossaryofTerms.md
- [x] 02 Project Execution and Planning
    - 02.01.TeamInformation.md
    - 02.02.ToolsandTechnology.md
    - 02.03.ProjectPlan.md
    - 02.04.BeststandardsandPractices.md
- [x] 03 System Requirements Analysis
    - 03.01.FunctionalRequirements.md
    - 03.02.Non-functionalRequirements.md
    - 03.03.On-ScreenAppearanceoflandingandotherpagesrequirements.md
    - 03.04.Wireframedesigns.md
- [x] 04 Functional Requirements Specification
    - 04.01--04.02.StakeholdersActorsGoals.md
    - 04.03.UserstoriesScenariosandUseCases.md
    - 04.04.SystemSequenceActivityDiagrams.md
- [x] 05 User Interface Specifications
    - 05.01.PreliminaryDesign.md
    - 05.02.UserEffortEstimation.md
- [x] 06 Static Design
    - 06.01.ClassModel.md
    - 06.02.SystemOperationContracts.md
    - 06.03.MathematicalModel.md
    - 06.04.EntityRelation.md
- [x] 07 Dynamic Design
    - 07.01.SequenceDiagrams.md
    - 07.02.InterfaceSpecification.md
    - 07.03.StateDiagrams.md
- [x] 08 System Architecture and System Design
    - 08.01.SubsystemsComponentDesignPatternIdentification.md
    - 08.02.MappingSubsystemstoHardwareDeploymentDiagram.md
    - 08.03.PersistentDataStorage.md
    - 08.04.NetworkProtocol.md
    - 08.05.GlobalControlFlow.md
    - 08.06.HardwareRequirement.md
- [x] 09 Algorithms and Data Structures
    - 09.01.Algorithms.md
    - 09.02.DataStructures.md
- [x] 10 User Interface Design and Implementation
    - 10.01.UserInterfaceDesign.md
    - 10.02.UserInterfaceImplementation.md
- [x] 11 Testing
    - 11.01.UnitTestArchitectureandStrategyFramework.md
    - 11.02.Unittestdefinitiontestdataselection.md
    - 11.03.SystemTestSpecification.md
    - 11.04.TestReportsperSprint.md
- [x] 12 Project Management
    - 12.01.ProjectPlan.md
    - 12.02.Riskmanagement.md

**Comment by nmcox** [comment]
We can apply the titles that are in the Syllabus

**Comment by mbroe** [comment]
On Sun, 15 Apr 2018 at 07:50 -0700, nmcox wrote:
> We can apply the titles that are in the Syllabus

Ah.  Thanks.  I should have checked the syllabus first; didn't.
