### ISSUE TITLE
01.01 Backgrounds

### ISSUE THREAD

**Issue by nmcox** [csi4999-mims/documentation#14]

**Comment by mbroe** [comment]
While looking through the issues for this sprint—and in pursuit of
low-hanging fruit—I stumbled upon this issue.  Please feel free to
tell me to get lost.

However, so long as I'm here, I'm curious: What needs to be done with
the background document?  In my opinion, it seems fairly complete.  Is
there something we want to touch on that was not already added in
2b5de12422f573563dc6a0d510e4a930e2f3567c?

**Comment by nmcox** [comment]
We may just want to expand on it and include some statistics and fancy fluff, but if everyone thinks it looks good to go then we can close it for now.

**Comment by mbroe** [comment]
Sent our current draft to Steve for review.  Awaiting response.
