### ISSUE TITLE
12.02 risk management

### ISSUE THREAD

**Issue by nmcox** [csi4999-mims/documentation#89]
review and finalize

**Comment by tcwatling** [comment]
Looks good to me

**Comment by minqianghu2** [comment]
It should be good

**Comment by mbroe** [comment]
Is this supposed to be the flow:

1. Risk Details
    1. Foo
    2. Bar
2. Risk Assessment
    1. Likelihood: 5
    2. Impact: 10
    3. Cost: 10
3. Rank: 60
4. Mitigation Plan: Foo bar baz.

Or is this supposed to be the flow:

1. Risk Details
    1. Foo
    2. Bar
2. Risk Assessment
    1. Likelihood: 5
    2. Impact: 10
    3. Cost: 10
    4. Rank: 60
3. Mitigation Plan: Foo bar baz.

**Comment by nmcox** [comment]
The first one. with  1-4

**Comment by mbroe** [comment]
Awesome, thanks.  That's the version that made it into v2.0.
